# Generated by Django 3.2.5 on 2021-08-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='user',
        ),
        migrations.DeleteModel(
            name='Auction_Listing',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
