# Generated by Django 3.2.5 on 2021-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210823_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=45)),
                ('Discription', models.CharField(max_length=1064)),
                ('Bid', models.IntegerField()),
                ('URL', models.URLField(null=True)),
                ('Category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('electronic device', 'Electronic Device'), ('toys', 'Toys'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=40)),
            ],
        ),
    ]
