# Generated by Django 3.2.5 on 2021-08-24 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_new_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Current_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_User', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='new_listing',
            old_name='Discription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='new_listing',
            old_name='Bid',
            new_name='Starting_Bid',
        ),
        migrations.RemoveField(
            model_name='new_listing',
            name='URL',
        ),
        migrations.AddField(
            model_name='new_listing',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='new_listing',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new_listing',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bidsss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Bid', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('Date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='new_listing',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
