# Generated by Django 3.2.5 on 2021-08-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210824_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_listing',
            name='Current_Bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
