# Generated by Django 3.2.5 on 2021-08-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_new_listing_current_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('Date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='new_listing',
            name='Image',
        ),
        migrations.AddField(
            model_name='new_listing',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new_listing',
            name='viewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_made_the_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='new_listing',
            name='Category',
            field=models.ForeignKey(choices=[('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Home Products', 'Home Products'), ('Toys', 'Toys'), ('Food and Beverages', 'Food and Beverages'), ('Other', 'Other')], on_delete=django.db.models.deletion.CASCADE, related_name='category_of_the_item', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='new_listing',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user_who_made_the_auction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bidsss',
        ),
        migrations.AddField(
            model_name='bids',
            name='Auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_made_by_the_user', to='auctions.new_listing'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_will_make_the_bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='new_listing',
            name='Overall_Bids',
            field=models.ManyToManyField(blank=True, related_name='all_the_bids', to='auctions.Bids'),
        ),
        migrations.AlterField(
            model_name='new_listing',
            name='Current_Bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.bids'),
        ),
    ]
