# Generated by Django 3.2.5 on 2021-08-27 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210825_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Current_User',
        ),
        migrations.RenameField(
            model_name='new_listing',
            old_name='Starting_Bid',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='new_listing',
            name='Overall_Bids',
        ),
        migrations.RemoveField(
            model_name='new_listing',
            name='URL',
        ),
        migrations.RemoveField(
            model_name='new_listing',
            name='viewer',
        ),
        migrations.AddField(
            model_name='new_listing',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='new_listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_listing',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='new_listing',
            name='Category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Home Products', 'Home Products'), ('Toys', 'Toys'), ('Food and Beverages', 'Food and Beverages'), ('Other', 'Other')], max_length=24),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.new_listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
