# Generated by Django 3.2.5 on 2021-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210827_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_listing',
            name='Image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
