# Generated by Django 3.2.5 on 2021-08-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_new_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=45)),
                ('Description', models.CharField(max_length=1064)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Price', models.IntegerField()),
                ('Image', models.URLField(blank=True, default=None, null=True)),
                ('Category', models.CharField(choices=[('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Home Products', 'Home Products'), ('Toys', 'Toys'), ('Food and Beverages', 'Food and Beverages'), ('Other', 'Other')], max_length=24)),
                ('closed', models.BooleanField(default=False)),
                ('Current_Bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.bids')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user_who_made_the_auction', to=settings.AUTH_USER_MODEL)),
                ('watcher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bids',
            name='Auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_made_by_the_user', to='auctions.newlisting'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.newlisting'),
        ),
        migrations.DeleteModel(
            name='New_Listing',
        ),
    ]
