# Generated by Django 3.2.5 on 2021-08-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210828_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlisting',
            name='watcher',
        ),
    ]
