# Generated by Django 3.2.5 on 2021-08-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_newlisting_watcher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewListing',
            new_name='Listing',
        ),
    ]
