# Generated by Django 3.2.5 on 2021-09-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_watchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Categories', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cat', to='auctions.category'),
        ),
    ]
