# Generated by Django 3.2.5 on 2021-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210922_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Home Products', 'Home Products'), ('Toys', 'Toys'), ('Food and Beverages', 'Food and Beverages'), ('Other', 'Other')], max_length=24),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
