# Generated by Django 3.2.5 on 2021-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Technology'), ('c', 'Home Products'), ('d', 'Toys'), ('e and Beverages', 'Food and Beverages'), ('f', 'Other')], max_length=24),
        ),
    ]
