# Generated by Django 3.2.5 on 2021-09-23 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
