# Generated by Django 3.2.5 on 2021-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bids_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Technology', 'Technology'), ('Home Products', 'Home Products'), ('Toys', 'Toys'), ('Food and Beverages', 'Food and Beverages'), ('Other', 'Other')], max_length=24),
        ),
    ]
