# Generated by Django 4.0.4 on 2022-06-04 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=1064)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='post_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
