# Generated by Django 4.0.4 on 2022-06-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_like_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
