# Generated by Django 4.0.4 on 2022-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='Genres',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Electro', 'Electro'), ('Other', 'Other')], default='Other', max_length=24),
        ),
    ]
