# Generated by Django 4.0.4 on 2022-06-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_songs_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='Genres',
        ),
        migrations.AddField(
            model_name='songs',
            name='Albums',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Electro', 'Electro'), ('90s', '90s'), ('Bollywood', 'Bollywood'), ('Other', 'Other')], default='Other', max_length=24),
        ),
    ]
