# Generated by Django 4.0.4 on 2022-06-30 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_songs_genres_songs_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='song_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songs',
            name='Albums',
            field=models.CharField(max_length=24),
        ),
    ]
