# Generated by Django 4.0.4 on 2022-06-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_songs_liked_by_alter_songs_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='Albums',
            new_name='albums',
        ),
    ]
