# Generated by Django 4.0.4 on 2022-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_songs_albums_songs_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='Albums',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Electro', 'Electro'), ('90s', '90s'), ('Classical', 'Classical'), ('Funk', 'Funk'), ('Bollywood', 'Bollywood'), ('Other', 'Other')], default='Other', max_length=24),
        ),
    ]
